name: Continuous Integration Build

on:
  pull_request:
    branches: [ master ]
#  push:
#    branches: [ master ]

jobs:
  ubuntu-build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Create build directory and run CMake
        run: |
          sudo apt-get -y install freeglut3-dev
          cmake -S . -B cmake_build_dir -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=cmake_install_dir
      - name: Build project
        run: |
          cmake --build cmake_build_dir --target install --config Release -- -j4
          tar czf superglu-latest-Ubuntu-gcc7-x64.tar.gz cmake_install_dir/*
      # - name: Run tests
      #   run: |
      #     cd cmake_build_dir
      #     ctest -C Release -VV
      - name: Create Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Ubuntu-Artifacts
          path: superglu-latest-Ubuntu-gcc7-x64.tar.gz
        if: always()

  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Create build directory and run CMake
        shell: cmd
        run: |
          cmake -S . -B cmake_build_dir -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=cmake_install_dir
      - name: Build project
        run: |
          cmake --build cmake_build_dir --target INSTALL --config Release -- /nologo /verbosity:minimal /maxcpucount:2 /property:MultiProcessorCompilation=true
          7z a -tzip superglu-latest-msvc16-x64.zip cmake_install_dir
      # - name: Run tests
      #   run: |
      #     cd cmake_build_dir
      #     ctest -C Release -VV
      - name: Create Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Windows-Artifacts
          path: superglu-latest-msvc16-x64.zip
        if: always()

#  macos-build:
#    name: MacOS Build
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Checkout submodules
#        run: git submodule update --init --recursive
#      - name: Create build directory and run CMake
#        run: |
#          cmake -S . -B cmake_build_dir -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=cmake_install_dir
#      - name: Build project
#        run: |
#          cmake --build cmake_build_dir --target install --config Release -- -j4
#          tar czf superglu-latest-macos-clang11-x64.tar.gz cmake_install_dir/*
#      # - name: Run tests
#      #   run: |
#      #     cd cmake_build_dir
#      #     ctest -C Release -VV
#      - name: Create Artifacts
#        uses: actions/upload-artifact@v1
#        with:
#          name: MacOS-Artifacts
#          path: superglu-latest-macos-clang11-x64.tar.gz
#        if: always()
